oecd_dictionary = {
    'Australia (AUS)':'Australia',
    'Austria (AUT)':'Austria',
    'Belgium (BEL)':'Belgium',
    'Canada (CAN)':'Canada',
    'Chile (CHL)':'Chile',
    'Czech Republic (CZE)':'Czech Republic',
    'Denmark (DNK)':'Denmark',
    'Estonia (EST)':'Estonia',
    'Finland (FIN)':'Finland',
    'France (FRA)':'France',
    'Germany (DEU)':'Germany',
    'Greece (GRC)':'Greece',
    'Hungary (HUN)':'Hungary',
    'Iceland (ISL)':'Iceland',
    'Ireland (IRL)':'Ireland',
    'Israel (ISR)':'Israel',
    'Italy (ITA)':'Italy',
    'Japan (JPN)':'Japan',
    'Korea (KOR)':'Korea',
    'Latvia (LVA)':'Latvia',
    'Lithuania (LTU)':'Lithuania',
    'Luxembourg (LUX)':'Luxembourg',
    'Mexico (MEX)':'Mexico',
    'Netherlands (NLD)':'Netherlands',
    'New Zealand (NZL)':'New Zealand',
    'Norway (NOR)':'Norway',
    'Poland (POL)':'Poland',
    'Portugal (PRT)':'Portugal',
    'Slovak Republic (SVK)':'Slovak Republic',
    'Slovenia (SVN)':'Slovenia',
    'Spain (ESP)':'Spain',
    'Sweden (SWE)':'Sweden',
    'Switzerland (CHE)':'Switzerland',
    'Turkey (TUR)':'Turkey',
    'United Kingdom (GBR)':'United Kingdom',
    'United States (USA)':'United States',
    'Argentina (ARG)':'Argentina',
    'Belize (BLZ)':'Belize',
    'Bolivia (BOL)':'Bolivia',
    'Brazil (BRA)':'Brazil',
    'Colombia (COL)':'Colombia',
    'Costa Rica (CRI)':'Costa Rica',
    'Dominican Republic (DOM)':'Dominican Republic',
    'Ecuador (ECU)':'Ecuador',
    'El Salvador (SLV)':'El Salvador',
    'Guatemala (GTM)':'Guatemala',
    'Guyana (GUY)':'Guyana',
    'Honduras (HND)':'Honduras',
    'Jamaica (JAM)':'Jamaica',
    'Panama (PAN)':'Panama',
    'Paraguay (PRY)':'Paraguay',
    'Peru (PER)':'Peru',
    'South Africa (ZAF)':'South Africa',
    'Suriname (SUR)':'Suriname',
    'Trinidad and Tobago (TTO)':'Trinidad and Tobago',
    'Uruguay (URY)':'Uruguay'
    }

eurostat_dictionary = {
    'EU27_2020':'European Union - 27 countries (from 2020)',
    'EA20':'Euro area – 20 countries (from 2023)',
    'EA19':'Euro area - 19 countries  (2015-2022)',
    'BE' : 'Belgium',
    'BG' : 'Bulgaria',
    'CZ' : 'Czechia',
    'DK' : 'Denmark',
    'DE' : 'Germany',
    'EE' : 'Estonia',
    'IE' : 'Ireland',
    'EL' : 'Greece',
    'ES' : 'Spain',
    'FR' : 'France',
    'HR' : 'Croatia',
    'IT' : 'Italy',
    'CY' : 'Cyprus',
    'LV' : 'Latvia',
    'LT' : 'Lithuania',
    'LU' : 'Luxembourg',
    'HU' : 'Hungary',
    'MT' : 'Malta',
    'NL' : 'Netherlands',
    'AT' : 'Austria',
    'PL' : 'Poland',
    'PT' : 'Portugal',
    'RO' : 'Romania',
    'SI' : 'Slovenia',
    'SK' : 'Slovakia',
    'FI' : 'Finland',
    'SE' : 'Sweden',
    'UK' : 'United Kingdom',
    'IS' : 'Iceland',
    'NO' : 'Norway',
    'LI' : 'Liechtenstein',
    'CH' : 'Switzerland',
    'ME' : 'Montenegro',
    'MK' : 'North Macedonia',
    'AL' : 'Albania',
    'RS' : 'Serbia',
    'TR' : 'Turkey',
    'BA' : 'Bosnia and Herzegovina',
    'XK' : 'Kosovo',
    'RU' : 'Russia',
    'AM' : 'Armenia',
    'AZ' : 'Azerbaijan',
    'DZ' : 'Algeria',
    'EG' : 'Egypt',
    'IL' : 'Israel',
    'JO' : 'Jordan',
    'BY' : 'Belarus',
    'MD' : 'Moldova',
    'LB' : 'Lebanon',
    'LY' : 'Libya',
    'MA' : 'Morocco',
    'PS' : 'Palestine',
    'GE' : 'Georgia',
    'UA' : 'Ukraine',
    'SY' : 'Syria',
    'TN' : 'Tunisia',
    'AR' : 'Argentina',
    'AU' : 'Australia',
    'BR' : 'Brazil',
    'CA' : 'Canada',
    'HK' : 'Hong Kong',
    'IN' : 'India',
    'JP' : 'Japan',
    'MX' : 'Mexico',
    'NG' : 'Nigeria',
    'NZ' : 'New Zealand',
    'SG' : 'Singapore',
    'ZA' : 'South Africa',
    'KR' : 'South Korea',
    'TW' : 'Taiwan',
    'US' : 'United States',
    'CN_X_HK' : 'China (except Hong Kong)'
    }

worldbank_dictionary = {
    'ABW' : 'Aruba',
    'AFG' : 'Afghanistan',
    'AGO' : 'Angola',
    'AIA' : 'Anguilla',
    'ALA' : 'Åland Islands',
    'ALB' : 'Albania',
    'AND' : 'Andorra',
    'ANT' : 'Netherlands Antilles',
    'ARE' : 'United Arab Emirates',
    'ARG' : 'Argentina',
    'ARM' : 'Armenia',
    'ASM' : 'American Samoa',
    'ATA' : 'Antarctica',
    'ATF' : 'French Southern Territories',
    'ATG' : 'Antigua and Barbuda',
    'AUS' : 'Australia',
    'AUT' : 'Austria',
    'AZE' : 'Azerbaijan',
    'BDI' : 'Burundi',
    'BEL' : 'Belgium',
    'BEN' : 'Benin',
    'BFA' : 'Burkina Faso',
    'BGD' : 'Bangladesh',
    'BGR' : 'Bulgaria',
    'BHR' : 'Bahrain',
    'BHS' : 'Bahamas',
    'BIH' : 'Bosnia and Herzegovina',
    'BLM' : 'Saint Barthélemy',
    'BLR' : 'Belarus',
    'BLZ' : 'Belize',
    'BMU' : 'Bermuda',
    'BOL' : 'Bolivia, Plurinational State of',
    'BRA' : 'Brazil',
    'BRB' : 'Barbados',
    'BRN' : 'Brunei Darussalam',
    'BTN' : 'Bhutan',
    'BVT' : 'Bouvet Island',
    'BWA' : 'Botswana',
    'CAF' : 'Central African Republic',
    'CAN' : 'Canada',
    'CCK' : 'Cocos (Keeling) Islands',
    'CHE' : 'Switzerland',
    'CHL' : 'Chile',
    'CHN' : 'China',
#    'CIV' : 'Côte d'Ivoire',
    'CMR' : 'Cameroon',
    'COD' : 'Congo, the Democratic Republic of the',
    'COG' : 'Congo',
    'COK' : 'Cook Islands',
    'COL' : 'Colombia',
    'COM' : 'Comoros',
    'CPV' : 'Cape Verde',
    'CRI' : 'Costa Rica',
    'CUB' : 'Cuba',
    'CXR' : 'Christmas Island',
    'CYM' : 'Cayman Islands',
    'CYP' : 'Cyprus',
    'CZE' : 'Czech Republic',
    'DEU' : 'Germany',
    'DJI' : 'Djibouti',
    'DMA' : 'Dominica',
    'DNK' : 'Denmark',
    'DOM' : 'Dominican Republic',
    'DZA' : 'Algeria',
    'ECU' : 'Ecuador',
    'EGY' : 'Egypt',
    'ERI' : 'Eritrea',
    'ESH' : 'Western Sahara',
    'ESP' : 'Spain',
    'EST' : 'Estonia',
    'ETH' : 'Ethiopia',
    'FIN' : 'Finland',
    'FJI' : 'Fiji',
    'FLK' : 'Falkland Islands (Malvinas)',
    'FRA' : 'France',
    'FRO' : 'Faroe Islands',
    'FSM' : 'Micronesia, Federated States of',
    'GAB' : 'Gabon',
    'GBR' : 'United Kingdom',
    'GEO' : 'Georgia',
    'GGY' : 'Guernsey',
    'GHA' : 'Ghana',
    'GIB' : 'Gibraltar',
    'GIN' : 'Guinea',
    'GLP' : 'Guadeloupe',
    'GMB' : 'Gambia',
    'GNB' : 'Guinea-Bissau',
    'GNQ' : 'Equatorial Guinea',
    'GRC' : 'Greece',
    'GRD' : 'Grenada',
    'GRL' : 'Greenland',
    'GTM' : 'Guatemala',
    'GUF' : 'French Guiana',
    'GUM' : 'Guam',
    'GUY' : 'Guyana',
    'HKG' : 'Hong Kong',
    'HMD' : 'Heard Island and McDonald Islands',
    'HND' : 'Honduras',
    'HRV' : 'Croatia',
    'HTI' : 'Haiti',
    'HUN' : 'Hungary',
    'IDN' : 'Indonesia',
    'IMN' : 'Isle of Man',
    'IND' : 'India',
    'IOT' : 'British Indian Ocean Territory',
    'IRL' : 'Ireland',
    'IRN' : 'Iran, Islamic Republic of',
    'IRQ' : 'Iraq',
    'ISL' : 'Iceland',
    'ISR' : 'Israel',
    'ITA' : 'Italy',
    'JAM' : 'Jamaica',
    'JEY' : 'Jersey',
    'JOR' : 'Jordan',
    'JPN' : 'Japan',
    'KAZ' : 'Kazakhstan',
    'KEN' : 'Kenya',
    'KGZ' : 'Kyrgyzstan',
    'KHM' : 'Cambodia',
    'KIR' : 'Kiribati',
    'KNA' : 'Saint Kitts and Nevis',
    'KOR' : 'Korea, Republic of',
    'KWT' : 'Kuwait',
#    'LAO' : 'Lao People's Democratic Republic',
    'LBN' : 'Lebanon',
    'LBR' : 'Liberia',
    'LBY' : 'Libyan Arab Jamahiriya',
    'LCA' : 'Saint Lucia',
    'LIE' : 'Liechtenstein',
    'LKA' : 'Sri Lanka',
    'LSO' : 'Lesotho',
    'LTU' : 'Lithuania',
    'LUX' : 'Luxembourg',
    'LVA' : 'Latvia',
    'MAC' : 'Macao',
    'MAF' : 'Saint Martin (French part)',
    'MAR' : 'Morocco',
    'MCO' : 'Monaco',
    'MDA' : 'Moldova, Republic of',
    'MDG' : 'Madagascar',
    'MDV' : 'Maldives',
    'MEX' : 'Mexico',
    'MHL' : 'Marshall Islands',
    'MKD' : 'Macedonia, the former Yugoslav Republic of',
    'MLI' : 'Mali',
    'MLT' : 'Malta',
    'MMR' : 'Myanmar',
    'MNE' : 'Montenegro',
    'MNG' : 'Mongolia',
    'MNP' : 'Northern Mariana Islands',
    'MOZ' : 'Mozambique',
    'MRT' : 'Mauritania',
    'MSR' : 'Montserrat',
    'MTQ' : 'Martinique',
    'MUS' : 'Mauritius',
    'MWI' : 'Malawi',
    'MYS' : 'Malaysia',
    'MYT' : 'Mayotte',
    'NAM' : 'Namibia',
    'NCL' : 'New Caledonia',
    'NER' : 'Niger',
    'NFK' : 'Norfolk Island',
    'NGA' : 'Nigeria',
    'NIC' : 'Nicaragua',
    'NIU' : 'Niue',
    'NLD' : 'Netherlands',
    'NOR' : 'Norway',
    'NPL' : 'Nepal',
    'NRU' : 'Nauru',
    'NZL' : 'New Zealand',
    'OMN' : 'Oman',
    'PAK' : 'Pakistan',
    'PAN' : 'Panama',
    'PCN' : 'Pitcairn',
    'PER' : 'Peru',
    'PHL' : 'Philippines',
    'PLW' : 'Palau',
    'PNG' : 'Papua New Guinea',
    'POL' : 'Poland',
    'PRI' : 'Puerto Rico',
#    'PRK' : 'Korea, Democratic People's Republic of',
    'PRT' : 'Portugal',
    'PRY' : 'Paraguay',
    'PSE' : 'Palestinian Territory, Occupied',
    'PYF' : 'French Polynesia',
    'QAT' : 'Qatar',
    'REU' : 'Réunion',
    'ROU' : 'Romania',
    'RUS' : 'Russian Federation',
    'RWA' : 'Rwanda',
    'SAU' : 'Saudi Arabia',
    'SDN' : 'Sudan',
    'SEN' : 'Senegal',
    'SGP' : 'Singapore',
    'SGS' : 'South Georgia and the South Sandwich Islands',
    'SHN' : 'Saint Helena, Ascension and Tristan da Cunha',
    'SJM' : 'Svalbard and Jan Mayen',
    'SLB' : 'Solomon Islands',
    'SLE' : 'Sierra Leone',
    'SLV' : 'El Salvador',
    'SMR' : 'San Marino',
    'SOM' : 'Somalia',
    'SPM' : 'Saint Pierre and Miquelon',
    'SRB' : 'Serbia',
    'STP' : 'Sao Tome and Principe',
    'SUR' : 'Suriname',
    'SVK' : 'Slovakia',
    'SVN' : 'Slovenia',
    'SWE' : 'Sweden',
    'SWZ' : 'Swaziland',
    'SYC' : 'Seychelles',
    'SYR' : 'Syrian Arab Republic',
    'TCA' : 'Turks and Caicos Islands',
    'TCD' : 'Chad',
    'TGO' : 'Togo',
    'THA' : 'Thailand',
    'TJK' : 'Tajikistan',
    'TKL' : 'Tokelau',
    'TKM' : 'Turkmenistan',
    'TLS' : 'Timor-Leste',
    'TON' : 'Tonga',
    'TTO' : 'Trinidad and Tobago',
    'TUN' : 'Tunisia',
    'TUR' : 'Turkey',
    'TUV' : 'Tuvalu',
    'TWN' : 'Taiwan, Province of China',
    'TZA' : 'Tanzania, United Republic of',
    'UGA' : 'Uganda',
    'UKR' : 'Ukraine',
    'UMI' : 'United States Minor Outlying Islands',
    'URY' : 'Uruguay',
    'USA' : 'United States',
    'UZB' : 'Uzbekistan',
    'VAT' : 'Holy See (Vatican City State)',
    'VCT' : 'Saint Vincent and the Grenadines',
    'VEN' : 'Venezuela, Bolivarian Republic of',
    'VGB' : 'Virgin Islands, British',
    'VIR' : 'Virgin Islands, U.S.',
    'VNM' : 'Viet Nam',
    'VUT' : 'Vanuatu',
    'WLF' : 'Wallis and Futuna',
    'WSM' : 'Samoa',
    'YEM' : 'Yemen',
    'ZAF' : 'South Africa',
    'ZMB' : 'Zambia',
    'ZWE' : 'Zimbabwe'}

country_geo_dic = {
    "Algeria": {"region": "Northern Africa", "continent": "Africa"},
    "Egypt": {"region": "Northern Africa", "continent": "Africa"},
    "Libya": {"region": "Northern Africa", "continent": "Africa"},
    "Morocco": {"region": "Northern Africa", "continent": "Africa"},
    "Sudan": {"region": "Northern Africa", "continent": "Africa"},
    "Tunisia": {"region": "Northern Africa", "continent": "Africa"},
    "Western Sahara": {"region": "Northern Africa", "continent": "Africa"},
    "British Indian Ocean Territory": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Burundi": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Comoros": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Djibouti": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Eritrea": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Ethiopia": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "French Southern Territories": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Kenya": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Madagascar": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Malawi": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Mauritius": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Mayotte": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Mozambique": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Réunion": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Rwanda": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Seychelles": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Somalia": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "South Sudan": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Uganda": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "United Republic of Tanzania": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Zambia": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Zimbabwe": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Angola": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Cameroon": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Central African Republic": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Chad": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Republic of the Congo": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Democratic Republic of the Congo": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Equatorial Guinea": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Gabon": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Sao Tome and Principe": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Botswana": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Eswatini [Swaziland]": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Lesotho": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Namibia": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "South Africa": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Benin": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Burkina Faso": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Cape Verde": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Ivory Coast": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Gambia": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Ghana": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Guinea": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Guinea-Bissau": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Liberia": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Mali": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Mauritania": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Niger": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Nigeria": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Saint Helena [Saint Helena, Ascension and Tristan da Cunha]": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Senegal": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Sierra Leone": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Togo": {"region": "Sub-Saharan Africa", "continent": "Africa"},
    "Anguilla": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Antigua and Barbuda": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Aruba": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Bahamas": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Barbados": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Bonaire, Sint Eustatius and Saba": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "British Virgin Islands": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Cayman Islands": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Cuba": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Curaçao": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Dominica": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Dominican Republic": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Grenada": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Guadeloupe": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Haiti": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Jamaica": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Martinique": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Montserrat": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Puerto Rico": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Saint Barthélemy": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Saint Kitts and Nevis": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Saint Lucia": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Saint Martin (French part)": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Saint Vincent and the Grenadines": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Sint Maarten (Dutch part)": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Trinidad and Tobago": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Turks and Caicos Islands": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "United States Virgin Islands": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Belize": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Costa Rica": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "El Salvador": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Guatemala": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Honduras": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Mexico": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Nicaragua": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Panama": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Argentina": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Bolivia (Plurinational State of)": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Bouvet Island": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Brazil": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Chile": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Colombia": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Ecuador": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Falkland Islands (Malvinas)": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "French Guiana": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Guyana": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Paraguay": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Peru": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "South Georgia and the South Sandwich Islands": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Suriname": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Uruguay": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Venezuela (Bolivarian Republic of)": {"region": "Latin America and the Caribbean", "continent": "Americas"},
    "Bermuda": {"region": "Northern America", "continent": "Americas"},
    "Canada": {"region": "Northern America", "continent": "Americas"},
    "Greenland": {"region": "Northern America", "continent": "Americas"},
    "Saint Pierre and Miquelon": {"region": "Northern America", "continent": "Americas"},
    "United States of America": {"region": "Northern America", "continent": "Americas"},
    "Antarctica": {"region": "", "continent": ""},
    "Kazakhstan": {"region": "Central Asia", "continent": "Asia"},
    "Kyrgyzstan": {"region": "Central Asia", "continent": "Asia"},
    "Tajikistan": {"region": "Central Asia", "continent": "Asia"},
    "Turkmenistan": {"region": "Central Asia", "continent": "Asia"},
    "Uzbekistan": {"region": "Central Asia", "continent": "Asia"},
    "China": {"region": "Eastern Asia", "continent": "Asia"},
    "China, Hong Kong Special Administrative Region": {"region": "Eastern Asia", "continent": "Asia"},
    "China, Macao Special Administrative Region": {"region": "Eastern Asia", "continent": "Asia"},
    "Democratic People's Republic of Korea [North Korea]": {"region": "Eastern Asia", "continent": "Asia"},
    "Japan": {"region": "Eastern Asia", "continent": "Asia"},
    "Mongolia": {"region": "Eastern Asia", "continent": "Asia"},
    "South Korea": {"region": "Eastern Asia", "continent": "Asia"},
    "Brunei Darussalam": {"region": "South-eastern Asia", "continent": "Asia"},
    "Cambodia": {"region": "South-eastern Asia", "continent": "Asia"},
    "Indonesia": {"region": "South-eastern Asia", "continent": "Asia"},
    "Lao People's Democratic Republic": {"region": "South-eastern Asia", "continent": "Asia"},
    "Malaysia": {"region": "South-eastern Asia", "continent": "Asia"},
    "Myanmar": {"region": "South-eastern Asia", "continent": "Asia"},
    "Philippines": {"region": "South-eastern Asia", "continent": "Asia"},
    "Singapore": {"region": "South-eastern Asia", "continent": "Asia"},
    "Thailand": {"region": "South-eastern Asia", "continent": "Asia"},
    "Timor-Leste [East Timor]": {"region": "South-eastern Asia", "continent": "Asia"},
    "Viet Nam": {"region": "South-eastern Asia", "continent": "Asia"},
    "Afghanistan": {"region": "Southern Asia", "continent": "Asia"},
    "Bangladesh": {"region": "Southern Asia", "continent": "Asia"},
    "Bhutan": {"region": "Southern Asia", "continent": "Asia"},
    "India": {"region": "Southern Asia", "continent": "Asia"},
    "Iran (Islamic Republic of)": {"region": "Southern Asia", "continent": "Asia"},
    "Maldives": {"region": "Southern Asia", "continent": "Asia"},
    "Nepal": {"region": "Southern Asia", "continent": "Asia"},
    "Pakistan": {"region": "Southern Asia", "continent": "Asia"},
    "Sri Lanka": {"region": "Southern Asia", "continent": "Asia"},
    "Armenia": {"region": "Western Asia", "continent": "Asia"},
    "Azerbaijan": {"region": "Western Asia", "continent": "Asia"},
    "Bahrain": {"region": "Western Asia", "continent": "Asia"},
    "Cyprus": {"region": "Western Asia", "continent": "Asia"},
    "Georgia": {"region": "Western Asia", "continent": "Asia"},
    "Iraq": {"region": "Western Asia", "continent": "Asia"},
    "Israel": {"region": "Western Asia", "continent": "Asia"},
    "Jordan": {"region": "Western Asia", "continent": "Asia"},
    "Kuwait": {"region": "Western Asia", "continent": "Asia"},
    "Lebanon": {"region": "Western Asia", "continent": "Asia"},
    "Oman": {"region": "Western Asia", "continent": "Asia"},
    "Qatar": {"region": "Western Asia", "continent": "Asia"},
    "Saudi Arabia": {"region": "Western Asia", "continent": "Asia"},
    "State of Palestine": {"region": "Western Asia", "continent": "Asia"},
    "Syrian Arab Republic": {"region": "Western Asia", "continent": "Asia"},
    "Türkiye": {"region": "Western Asia", "continent": "Asia"},
    "United Arab Emirates": {"region": "Western Asia", "continent": "Asia"},
    "Yemen": {"region": "Western Asia", "continent": "Asia"},
    "Belarus": {"region": "Eastern Europe", "continent": "Europe"},
    "Bulgaria": {"region": "Eastern Europe", "continent": "Europe"},
    "Czechia": {"region": "Eastern Europe", "continent": "Europe"},
    "Hungary": {"region": "Eastern Europe", "continent": "Europe"},
    "Poland": {"region": "Eastern Europe", "continent": "Europe"},
    "Republic of Moldova": {"region": "Eastern Europe", "continent": "Europe"},
    "Romania": {"region": "Eastern Europe", "continent": "Europe"},
    "Russian Federation": {"region": "Eastern Europe", "continent": "Europe"},
    "Slovakia": {"region": "Eastern Europe", "continent": "Europe"},
    "Ukraine": {"region": "Eastern Europe", "continent": "Europe"},
    "Åland Islands": {"region": "Northern Europe", "continent": "Europe"},
    "Guernsey": {"region": "Northern Europe", "continent": "Europe"},
    "Jersey": {"region": "Northern Europe", "continent": "Europe"},
    "Sark": {"region": "Northern Europe", "continent": "Europe"},
    "Denmark": {"region": "Northern Europe", "continent": "Europe"},
    "Estonia": {"region": "Northern Europe", "continent": "Europe"},
    "Faroe Islands": {"region": "Northern Europe", "continent": "Europe"},
    "Finland": {"region": "Northern Europe", "continent": "Europe"},
    "Iceland": {"region": "Northern Europe", "continent": "Europe"},
    "Ireland": {"region": "Northern Europe", "continent": "Europe"},
    "Isle of Man": {"region": "Northern Europe", "continent": "Europe"},
    "Latvia": {"region": "Northern Europe", "continent": "Europe"},
    "Lithuania": {"region": "Northern Europe", "continent": "Europe"},
    "Norway": {"region": "Northern Europe", "continent": "Europe"},
    "Svalbard and Jan Mayen Islands": {"region": "Northern Europe", "continent": "Europe"},
    "Sweden": {"region": "Northern Europe", "continent": "Europe"},
    "United Kingdom of Great Britain and Northern Ireland": {"region": "Northern Europe", "continent": "Europe"},
    "Albania": {"region": "Southern Europe", "continent": "Europe"},
    "Andorra": {"region": "Southern Europe", "continent": "Europe"},
    "Bosnia and Herzegovina": {"region": "Southern Europe", "continent": "Europe"},
    "Croatia": {"region": "Southern Europe", "continent": "Europe"},
    "Gibraltar": {"region": "Southern Europe", "continent": "Europe"},
    "Greece": {"region": "Southern Europe", "continent": "Europe"},
    "Vatican City": {"region": "Southern Europe", "continent": "Europe"},
    "Italy": {"region": "Southern Europe", "continent": "Europe"},
    "Malta": {"region": "Southern Europe", "continent": "Europe"},
    "Montenegro": {"region": "Southern Europe", "continent": "Europe"},
    "North Macedonia": {"region": "Southern Europe", "continent": "Europe"},
    "Portugal": {"region": "Southern Europe", "continent": "Europe"},
    "San Marino": {"region": "Southern Europe", "continent": "Europe"},
    "Serbia": {"region": "Southern Europe", "continent": "Europe"},
    "Slovenia": {"region": "Southern Europe", "continent": "Europe"},
    "Spain": {"region": "Southern Europe", "continent": "Europe"},
    "Austria": {"region": "Western Europe", "continent": "Europe"},
    "Belgium": {"region": "Western Europe", "continent": "Europe"},
    "France": {"region": "Western Europe", "continent": "Europe"},
    "Germany": {"region": "Western Europe", "continent": "Europe"},
    "Liechtenstein": {"region": "Western Europe", "continent": "Europe"},
    "Luxembourg": {"region": "Western Europe", "continent": "Europe"},
    "Monaco": {"region": "Western Europe", "continent": "Europe"},
    "Netherlands": {"region": "Western Europe", "continent": "Europe"},
    "Switzerland": {"region": "Western Europe", "continent": "Europe"},
    "Australia": {"region": "Australia and New Zealand", "continent": "Oceania"},
    "Christmas Island": {"region": "Australia and New Zealand", "continent": "Oceania"},
    "Cocos (Keeling) Islands": {"region": "Australia and New Zealand", "continent": "Oceania"},
    "Heard Island and McDonald Islands": {"region": "Australia and New Zealand", "continent": "Oceania"},
    "New Zealand": {"region": "Australia and New Zealand", "continent": "Oceania"},
    "Norfolk Island": {"region": "Australia and New Zealand", "continent": "Oceania"},
    "Fiji": {"region": "Melanesia", "continent": "Oceania"},
    "New Caledonia": {"region": "Melanesia", "continent": "Oceania"},
    "Papua New Guinea": {"region": "Melanesia", "continent": "Oceania"},
    "Solomon Islands": {"region": "Melanesia", "continent": "Oceania"},
    "Vanuatu": {"region": "Melanesia", "continent": "Oceania"},
    "Guam": {"region": "Micronesia", "continent": "Oceania"},
    "Kiribati": {"region": "Micronesia", "continent": "Oceania"},
    "Marshall Islands": {"region": "Micronesia", "continent": "Oceania"},
    "Micronesia (Federated States of)": {"region": "Micronesia", "continent": "Oceania"},
    "Nauru": {"region": "Micronesia", "continent": "Oceania"},
    "Northern Mariana Islands": {"region": "Micronesia", "continent": "Oceania"},
    "Palau": {"region": "Micronesia", "continent": "Oceania"},
    "United States Minor Outlying Islands": {"region": "Micronesia", "continent": "Oceania"},
    "American Samoa": {"region": "Polynesia", "continent": "Oceania"},
    "Cook Islands": {"region": "Polynesia", "continent": "Oceania"},
    "French Polynesia": {"region": "Polynesia", "continent": "Oceania"},
    "Niue": {"region": "Polynesia", "continent": "Oceania"},
    "Pitcairn [Pitcairn Islands]": {"region": "Polynesia", "continent": "Oceania"},
    "Samoa": {"region": "Polynesia", "continent": "Oceania"},
    "Tokelau": {"region": "Polynesia", "continent": "Oceania"},
    "Tonga": {"region": "Polynesia", "continent": "Oceania"},
    "Tuvalu": {"region": "Polynesia", "continent": "Oceania"},
    "Wallis and Futuna Islands": {"region": "Polynesia", "continent": "Oceania"}}


countries_and_currencies = [
 {'Abbreviation': 'UAE','World Countries': 'United Arab Emirates','Currency': 'Dirham','Symbol': 'AED','Sign': 'د.إ.\u200f', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'AFG','World Countries': 'Afghanistan','Currency': 'Afghani','Symbol': 'AFN','Sign': '؋', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'AL','World Countries': 'Albania','Currency': 'Albanian Lek','Symbol': 'ALL','Sign': 'Lek', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'ARM','World Countries': 'Armenia','Currency': 'Dram','Symbol': 'AMD','Sign': '֏', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'CW','World Countries': 'Curaçao','Currency': 'Netherlands Antillean Guilder','Symbol': 'ANG','Sign': 'ƒ', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'AGO','World Countries': 'Angola','Currency': 'Kwanza','Symbol': 'AOA','Sign': 'Kz', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'AR','World Countries': 'Argentina','Currency': 'Argentine Peso','Symbol': 'ARS','Sign': '$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'AU','World Countries': 'Australia','Currency': 'Australian Dollar','Symbol': 'AUD','Sign': '$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'ABW','World Countries': 'Aruba','Currency': 'Florin','Symbol': 'AWG','Sign': 'ƒ', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'AZE','World Countries': 'Azerbaijan','Currency': 'Manat','Symbol': 'AZN','Sign': '₼', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'BA','World Countries': 'Bosnia and Herzegovina','Currency': 'Convertible Mark','Symbol': 'BAM','Sign': 'KM', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'BRB','World Countries': 'Barbados','Currency': 'Dollar','Symbol': 'BBD','Sign': '$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'BGD','World Countries': 'Bangladesh','Currency': 'Taka','Symbol': 'BDT','Sign': '৳', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'BG','World Countries': 'Bulgaria','Currency': 'Bulgarian Lev','Symbol': 'BGN','Sign': 'лв', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'BH','World Countries': 'Bahrain','Currency': 'Bahraini Dinar','Symbol': 'BHD','Sign': '.د.ب', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'BDI','World Countries': 'Burundi','Currency': 'Franc','Symbol': 'BIF','Sign': 'FBu', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'BM','World Countries': 'Bermuda','Currency': 'Bermudian Dollar','Symbol': 'BMD','Sign': '$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'BRN','World Countries': 'Brunei','Currency': 'Dollar','Symbol': 'BND','Sign': '$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'BOL','World Countries': 'Bolivia','Currency': 'Boliviano','Symbol': 'BOB','Sign': 'Bs.', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'BR','World Countries': 'Brazil','Currency': 'Brazilian Real','Symbol': 'BRL','Sign': 'R$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'BS','World Countries': 'Bahamas','Currency': 'Bahamian Dollar','Symbol': 'BSD','Sign': '$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'BTN','World Countries': 'Bhutan','Currency': 'Ngultrum','Symbol': 'BTN','Sign': 'Nu.', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'BWA','World Countries': 'Botswana','Currency': 'Pula','Symbol': 'BWP','Sign': 'P', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'BY','World Countries': 'Belarus','Currency': 'Belarusian Ruble','Symbol': 'BYN','Sign': 'Br', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'BLZ','World Countries': 'Belize','Currency': 'Dollar','Symbol': 'BZD','Sign': 'BZ$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'CA','World Countries': 'Canada','Currency': 'Canadian Dollar','Symbol': 'CAD','Sign': '$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'COD','World Countries': 'Democratic Republic of Congo','Currency': 'Franc','Symbol': 'CDF','Sign': 'FC', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'LI','World Countries': 'Liechtenstein','Currency': 'Swiss Franc','Symbol': 'CHF','Sign': 'Fr', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'CH','World Countries': 'Switzerland','Currency': 'Swiss Franc','Symbol': 'CHF','Sign': 'Fr', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'CL','World Countries': 'Chile','Currency': 'Chilean Peso','Symbol': 'CLP','Sign': '$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'CN','World Countries': 'China','Currency': 'Chinese Yuan','Symbol': 'CNY','Sign': '¥', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'CO','World Countries': 'Colombia','Currency': 'Colombian Peso','Symbol': 'COP','Sign': '$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'CRI','World Countries': 'Costa Rica','Currency': 'Colon','Symbol': 'CRC','Sign': '₡', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'CUB','World Countries': 'Cuba','Currency': 'Peso','Symbol': 'CUP','Sign': '$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'CPV','World Countries': 'Cape Verde','Currency': 'Escudo','Symbol': 'CVE','Sign': '$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'CZ','World Countries': 'Czech Republic','Currency': 'Czech Koruna','Symbol': 'CZK','Sign': 'Kč', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'DJI','World Countries': 'Djibouti','Currency': 'Franc','Symbol': 'DJF','Sign': 'Fdj', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'DK','World Countries': 'Denmark','Currency': 'Danish Krone','Symbol': 'DKK','Sign': 'kr', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'DO','World Countries': 'Dominican Republic','Currency': 'Dominican Peso','Symbol': 'DOP','Sign': '$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'DZA','World Countries': 'Algeria','Currency': 'Dinar','Symbol': 'DZD','Sign': 'د.ج.', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'EG','World Countries': 'Egypt','Currency': 'Egyptian Pound','Symbol': 'EGP','Sign': 'ج.م', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'ERI','World Countries': 'Eritrea','Currency': 'Nakfa','Symbol': 'ERN','Sign': 'Nfk', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'ETH','World Countries': 'Ethiopia','Currency': 'Birr','Symbol': 'ETB','Sign': 'Br', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'AD','World Countries': 'Andorra','Currency': 'Euro','Symbol': 'EUR','Sign': '€', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'AT','World Countries': 'Austria','Currency': 'Euro','Symbol': 'EUR','Sign': '€', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'BE','World Countries': 'Belgium','Currency': 'Euro','Symbol': 'EUR','Sign': '€', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'CY','World Countries': 'Cyprus','Currency': 'Euro','Symbol': 'EUR','Sign': '€', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'EE','World Countries': 'Estonia','Currency': 'Euro','Symbol': 'EUR','Sign': '€', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'FI','World Countries': 'Finland','Currency': 'Euro','Symbol': 'EUR','Sign': '€', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'FR','World Countries': 'France','Currency': 'Euro','Symbol': 'EUR','Sign': '€', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'DE','World Countries': 'Germany','Currency': 'Euro','Symbol': 'EUR','Sign': '€', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'GR','World Countries': 'Greece','Currency': 'Euro','Symbol': 'EUR','Sign': '€', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'IE','World Countries': 'Ireland','Currency': 'Euro','Symbol': 'EUR','Sign': '€', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'IT','World Countries': 'Italy','Currency': 'Euro','Symbol': 'EUR','Sign': '€', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'XK','World Countries': 'Kosovo','Currency': 'Euro','Symbol': 'EUR','Sign': '€', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'LV','World Countries': 'Latvia','Currency': 'Euro','Symbol': 'EUR','Sign': '€', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'LT','World Countries': 'Lithuania','Currency': 'Euro','Symbol': 'EUR','Sign': '€', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'LU','World Countries': 'Luxembourg','Currency': 'Euro','Symbol': 'EUR','Sign': '€', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'MT','World Countries': 'Malta','Currency': 'Euro','Symbol': 'EUR','Sign': '€', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'MC','World Countries': 'Monaco','Currency': 'Euro','Symbol': 'EUR','Sign': '€', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'ME','World Countries': 'Montenegro','Currency': 'Euro','Symbol': 'EUR','Sign': '€', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'NL','World Countries': 'Netherlands','Currency': 'Euro','Symbol': 'EUR','Sign': '€', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'PT','World Countries': 'Portugal','Currency': 'Euro','Symbol': 'EUR','Sign': '€', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'SM','World Countries': 'San Marino','Currency': 'Euro','Symbol': 'EUR','Sign': '€', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'SK','World Countries': 'Slovakia','Currency': 'Euro','Symbol': 'EUR','Sign': '€', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'SI','World Countries': 'Slovenia','Currency': 'Euro','Symbol': 'EUR','Sign': '€', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'ES','World Countries': 'Spain','Currency': 'Euro','Symbol': 'EUR','Sign': '€', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'VA','World Countries': 'Vatican City','Currency': 'Euro','Symbol': 'EUR','Sign': '€', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'FJI','World Countries': 'Fiji','Currency': 'Dollar','Symbol': 'FJD','Sign': '$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'FLK','World Countries': 'Falkland Islands','Currency': 'Pound','Symbol': 'FKP','Sign': '£', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'FRO','World Countries': 'Faroe Islands','Currency': 'Krone','Symbol': 'FOK','Sign': 'kr', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'IM','World Countries': 'Isle of Man','Currency': 'British Pound','Symbol': 'IMP','Sign': '£', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'U.K.','World Countries': 'United Kingdom','Currency': 'Pound Sterling','Symbol': 'GBP','Sign': '£', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'GEO','World Countries': 'Georgia','Currency': 'Lari','Symbol': 'GEL','Sign': '₾', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'GGY','World Countries': 'Guernsey','Currency': 'Pound','Symbol': 'GGP','Sign': '£', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'GHA','World Countries': 'Ghana','Currency': 'Cedi','Symbol': 'GHS','Sign': '₵', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'GI','World Countries': 'Gibraltar','Currency': 'Gibraltar Pound','Symbol': 'GIP','Sign': '£', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'GMB','World Countries': 'Gambia','Currency': 'Dalasi','Symbol': 'GMD','Sign': 'D', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'GIN','World Countries': 'Guinea','Currency': 'Franc','Symbol': 'GNF','Sign': 'FG', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'GTM','World Countries': 'Guatemala','Currency': 'Quetzal','Symbol': 'GTQ','Sign': 'Q', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'GUY','World Countries': 'Guyana','Currency': 'Dollar','Symbol': 'GYD','Sign': '$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'HK','World Countries': 'Hong Kong','Currency': 'Hong Kong Dollar','Symbol': 'HKD','Sign': '$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'HND','World Countries': 'Honduras','Currency': 'Lempira','Symbol': 'HNL','Sign': 'L', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'HR','World Countries': 'Croatia','Currency': 'Croatian Kuna','Symbol': 'HRK','Sign': 'kn', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'HTI','World Countries': 'Haiti','Currency': 'Gourde','Symbol': 'HTG','Sign': 'G', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'HU','World Countries': 'Hungary','Currency': 'Hungarian Forint','Symbol': 'HUF','Sign': 'Ft', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'ID','World Countries': 'Indonesia','Currency': 'Indonesian Rupiah','Symbol': 'IDR','Sign': 'Rp', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'IL','World Countries': 'Israel','Currency': 'Israeli Shekel','Symbol': 'ILS','Sign': '₪', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'IN','World Countries': 'India','Currency': 'Indian Rupee','Symbol': 'INR','Sign': '₹', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'IRQ','World Countries': 'Iraq','Currency': 'Dinar','Symbol': 'IQD','Sign': 'ع.د.', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'IRN','World Countries': 'Iran','Currency': 'Rial','Symbol': 'IRR','Sign': '﷼', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'IS','World Countries': 'Iceland','Currency': 'Icelandic Krona','Symbol': 'ISK','Sign': 'kr', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'JEY','World Countries': 'Jersey','Currency': 'Pound','Symbol': 'JEP','Sign': '£', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'JAM','World Countries': 'Jamaica','Currency': 'Dollar','Symbol': 'JMD','Sign': 'J$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'JO','World Countries': 'Jordan','Currency': 'Jordanian Dinar','Symbol': 'JOD','Sign': 'د.ا', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'JP','World Countries': 'Japan','Currency': 'Japanese Yen','Symbol': 'JPY','Sign': '¥', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'KEN','World Countries': 'Kenya','Currency': 'Shilling','Symbol': 'KES','Sign': 'KSh', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'KGZ','World Countries': 'Kyrgyzstan','Currency': 'Som','Symbol': 'KGS','Sign': 'som', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'KHM','World Countries': 'Cambodia','Currency': 'Riel','Symbol': 'KHR','Sign': '៛', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'KIR','World Countries': 'Kiribati','Currency': 'Dollar','Symbol': 'KID','Sign': '$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'COM','World Countries': 'Comoros','Currency': 'Franc','Symbol': 'KMF','Sign': 'CF', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'KR','World Countries': 'South Korea','Currency': 'South Korean Won','Symbol': 'KRW','Sign': '₩', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'KW','World Countries': 'Kuwait','Currency': 'Kuwaiti Dinar','Symbol': 'KWD','Sign': 'د.ك', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'KY','World Countries': 'Cayman Islands','Currency': 'Cayman Islands Dollar','Symbol': 'KYD','Sign': '$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'KZ','World Countries': 'Kazakhstan','Currency': 'Kazakhstani Tenge','Symbol': 'KZT','Sign': '₸', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'LAO','World Countries': 'Laos','Currency': 'Kip','Symbol': 'LAK','Sign': '₭', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'LB','World Countries': 'Lebanon','Currency': 'Lebanese Pound','Symbol': 'LBP','Sign': 'ل.ل', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'LK','World Countries': 'Sri Lanka','Currency': 'Sri Lankan Rupee','Symbol': 'LKR','Sign': 'Rs', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'LBR','World Countries': 'Liberia','Currency': 'Dollar','Symbol': 'LRD','Sign': '$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'LSO','World Countries': 'Lesotho','Currency': 'Loti','Symbol': 'LSL','Sign': 'L', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'LBY','World Countries': 'Libya','Currency': 'Dinar','Symbol': 'LYD','Sign': 'ل.د.', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'MA','World Countries': 'Morocco','Currency': 'Moroccan Dirham','Symbol': 'MAD','Sign': 'د.م', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'MD','World Countries': 'Moldova','Currency': 'Moldovan Leu','Symbol': 'MDL','Sign': 'lei', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'MDG','World Countries': 'Madagascar','Currency': 'Ariary','Symbol': 'MGA','Sign': 'Ar', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'MK','World Countries': 'North Macedonia','Currency': 'Macedonian Denar','Symbol': 'MKD','Sign': 'ден', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'MMR','World Countries': 'Myanmar (Burma)','Currency': 'Kyat','Symbol': 'MMK','Sign': 'K', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'MNG','World Countries': 'Mongolia','Currency': 'Tughrik','Symbol': 'MNT','Sign': '₮', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'MAC','World Countries': 'Macau','Currency': 'Pataca','Symbol': 'MOP','Sign': 'MOP$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'MRT','World Countries': 'Mauritania','Currency': 'Ouguiya','Symbol': 'MRU','Sign': 'UM', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'MU','World Countries': 'Mauritius','Currency': 'Mauritian Rupee','Symbol': 'MUR','Sign': '₨', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'MDV','World Countries': 'Maldives','Currency': 'Rufiyaa','Symbol': 'MVR','Sign': 'Rf', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'MWI','World Countries': 'Malawi','Currency': 'Kwacha','Symbol': 'MWK','Sign': 'MK', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'MX','World Countries': 'Mexico','Currency': 'Mexican Peso','Symbol': 'MXN','Sign': '$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'MY','World Countries': 'Malaysia','Currency': 'Malaysian Ringgit','Symbol': 'MYR','Sign': 'RM', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'MOZ','World Countries': 'Mozambique','Currency': 'Metical','Symbol': 'MZN','Sign': 'MT', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': None,'World Countries': 'Namibia','Currency': 'Namibian Dollar','Symbol': 'NAD','Sign': '$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'NGA','World Countries': 'Nigeria','Currency': 'Naira','Symbol': 'NGN','Sign': '₦', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'NIC','World Countries': 'Nicaragua','Currency': 'Cordoba','Symbol': 'NIO','Sign': 'C$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'NO','World Countries': 'Norway','Currency': 'Norwegian Krone','Symbol': 'NOK','Sign': 'kr', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'NPL','World Countries': 'Nepal','Currency': 'Rupee','Symbol': 'NPR','Sign': 'रू', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': None,'World Countries': 'International Monetary Fund','Currency': 'Special Drawing Rights','Symbol': None,'Sign': 'XDR', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'NZ','World Countries': 'New Zealand','Currency': 'New Zealand Dollar','Symbol': 'NZD','Sign': '$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'OM','World Countries': 'Oman','Currency': 'Omani Rial','Symbol': 'OMR','Sign': 'ر.ع', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'PA','World Countries': 'Panama','Currency': 'Panamanian Balboa','Symbol': 'PAB','Sign': 'B/.', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'PE','World Countries': 'Peru','Currency': 'Peruvian Sol','Symbol': 'PEN','Sign': 'S/', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'PNG','World Countries': 'Papua New Guinea','Currency': 'Kina','Symbol': 'PGK','Sign': 'K', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'PH','World Countries': 'Philippines','Currency': 'Philippine Peso','Symbol': 'PHP','Sign': '₱', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'PK','World Countries': 'Pakistan','Currency': 'Pakistani Rupee','Symbol': 'PKR','Sign': '₨', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'PL','World Countries': 'Poland','Currency': 'Polish Złoty','Symbol': 'PLN','Sign': 'zł', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'PY','World Countries': 'Paraguay','Currency': 'Paraguayan Guarani','Symbol': 'PYG','Sign': '₲', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'QA','World Countries': 'Qatar','Currency': 'Qatari Riyal','Symbol': 'QAR','Sign': 'ر.ق', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'RO','World Countries': 'Romania','Currency': 'Romanian Leu','Symbol': 'RON','Sign': 'lei', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'RS','World Countries': 'Serbia','Currency': 'Serbian Dinar','Symbol': 'RSD','Sign': 'РСД', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'RU','World Countries': 'Russia','Currency': 'Russian Ruble','Symbol': 'RUB','Sign': '₽', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'RWA','World Countries': 'Rwanda','Currency': 'Franc','Symbol': 'RWF','Sign': 'FRw', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'SAU','World Countries': 'Saudi Arabia','Currency': 'Riyal','Symbol': 'SAR','Sign': 'ر.س.', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'SLB','World Countries': 'Solomon Islands','Currency': 'Dollar','Symbol': 'SBD','Sign': '$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'SYC','World Countries': 'Seychelles','Currency': 'Rupee','Symbol': 'SCR','Sign': '₨', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'SDN','World Countries': 'Sudan','Currency': 'Pound','Symbol': 'SDG','Sign': '£', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'SE','World Countries': 'Sweden','Currency': 'Swedish Krona','Symbol': 'SEK','Sign': 'kr', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'SGP','World Countries': 'Singapore','Currency': 'Dollar','Symbol': 'SGD','Sign': '$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'SHN','World Countries': 'Saint Helena','Currency': 'Pound','Symbol': 'SHP','Sign': '£', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'SLE','World Countries': 'Sierra Leone','Currency': 'Leone','Symbol': 'SLE','Sign': 'Le', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'SLE','World Countries': 'Somalia','Currency': 'Shilling','Symbol': 'SLL','Sign': 'S', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': None,'World Countries': 'Somaliland','Currency': 'Shilling','Symbol': 'SOS','Sign': 'S', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'SUR','World Countries': 'Suriname','Currency': 'Dollar','Symbol': 'SRD','Sign': '$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'SSD','World Countries': 'South Sudan','Currency': 'Pound','Symbol': 'SSP','Sign': '£', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'STP','World Countries': 'São Tomé and Príncipe','Currency': 'Dobra','Symbol': 'STN','Sign': 'Db', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'SYR','World Countries': 'Syria','Currency': 'Pound','Symbol': 'SYP','Sign': '£', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'SWZ','World Countries': 'Eswatini (Swaziland)','Currency': 'Lilangeni','Symbol': 'SZL','Sign': 'E', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'TH','World Countries': 'Thailand','Currency': 'Thai Baht','Symbol': 'THB','Sign': '฿', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'TJK','World Countries': 'Tajikistan','Currency': 'Somoni','Symbol': 'TJS','Sign': 'SM', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'TKM','World Countries': 'Turkmenistan','Currency': 'Manat','Symbol': 'TMT','Sign': 'm', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'TN','World Countries': 'Tunisia','Currency': 'Tunisian Dinar','Symbol': 'TND','Sign': 'د.ت', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'TON','World Countries': 'Tonga','Currency': "Pa'anga",'Symbol': 'TOP','Sign': 'T$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'TR','World Countries': 'Turkey','Currency': 'Turkish Lira','Symbol': 'TRY','Sign': '₺', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'TTO','World Countries': 'Trinidad and Tobago','Currency': 'Dollar','Symbol': 'TTD','Sign': '$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'TUV','World Countries': 'Tuvalu','Currency': 'Dollar','Symbol': 'TVD','Sign': '$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'TW','World Countries': 'Taiwan','Currency': 'New Taiwan Dollar','Symbol': 'TWD','Sign': 'NT$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'TZA','World Countries': 'Tanzania','Currency': 'Shilling','Symbol': 'TZS','Sign': 'TSh', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'UA','World Countries': 'Ukraine','Currency': 'Ukrainian Hryvnia','Symbol': 'UAH','Sign': '₴', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'UGA','World Countries': 'Uganda','Currency': 'Shilling','Symbol': 'UGX','Sign': 'USh', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'VG','World Countries': 'British Virgin Islands','Currency': 'US Dollar','Symbol': 'USD','Sign': '$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'EC','World Countries': 'Ecuador','Currency': 'US Dollar','Symbol': 'USD','Sign': '$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'U.S.','World Countries': 'United States','Currency': 'US Dollar','Symbol': 'USD','Sign': '$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'URY','World Countries': 'Uruguay','Currency': 'Peso','Symbol': 'UYU','Sign': '$U', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'UZB','World Countries': 'Uzbekistan','Currency': 'Som','Symbol': 'UZS','Sign': "so'm", 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'VE','World Countries': 'Venezuela','Currency': 'Venezuelan Bolivar','Symbol': 'VES','Sign': 'Bs.S', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'VNM','World Countries': 'Vietnam','Currency': 'Dong','Symbol': 'VND','Sign': '₫', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'VUT','World Countries': 'Vanuatu','Currency': 'Vatu','Symbol': 'VUV','Sign': 'VT', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'WS','World Countries': 'Western Samoa','Currency': 'Tala','Symbol': 'WST','Sign': 'T', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'CAF','World Countries': 'Central African CFA franc','Currency': 'Franc','Symbol': 'XAF','Sign': 'FCFA', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': None,'World Countries': 'East Caribbean Dollar','Currency': 'Dollar','Symbol': 'XCD','Sign': '$', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': None,'World Countries': 'West African CFA franc','Currency': 'Franc','Symbol': 'XOF','Sign': 'CFA', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': None,'World Countries': 'CFP Franc','Currency': 'Franc','Symbol': 'XPF','Sign': 'F', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'YEM','World Countries': 'Yemen','Currency': 'Rial','Symbol': 'YER','Sign': '﷼', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'ZA','World Countries': 'South Africa','Currency': 'South African Rand','Symbol': 'ZAR','Sign': 'R', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'ZMB','World Countries': 'Zambia','Currency': 'Kwacha','Symbol': 'ZMW','Sign': 'ZK', 'Currency target': None,'ExchRate': None},
 {'Abbreviation': 'ZWE','World Countries': 'Zimbabwe','Currency': 'Dollar','Symbol': 'ZWL','Sign': '$', 'Currency target': None,'ExchRate': None}
]